# Generated by Django 4.0.6 on 2022-07-14 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter author first name', max_length=100, verbose_name='The author first name')),
                ('last_name', models.CharField(help_text='Enter author last name', max_length=100, verbose_name='The author last name')),
                ('date_of_birth', models.CharField(blank=True, help_text='Enter date of birth', max_length=20, null=True, verbose_name='Date of birth')),
                ('date_of_death', models.CharField(blank=True, help_text='Enter date of death', max_length=20, null=True, verbose_name='Date of death')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title', max_length=200, verbose_name='Book title')),
                ('summary', models.TextField(help_text='Enter a short description', max_length=1000, verbose_name='Annotation')),
                ('isbn', models.CharField(help_text='Should be 13 symbols', max_length=13, verbose_name='ISBN of the book')),
                ('author', models.ManyToManyField(help_text='Select the author', null=True, to='catalog.author', verbose_name="Book's author")),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the book genre', max_length=150, verbose_name='The book genre')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the book language', max_length=20, verbose_name='The book language')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the book status', max_length=20, verbose_name='Status of the book')),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_num', models.CharField(help_text='Enter inventory number', max_length=20, null=True)),
                ('imprint', models.CharField(help_text='Enter publisher and publish date', max_length=200, verbose_name='Publisher')),
                ('due_back', models.DateField(blank=True, help_text='Enter date of status ending', null=True, verbose_name='Status ending date')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.book')),
                ('status', models.ForeignKey(help_text='Change status', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.status', verbose_name='Status of the book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(help_text='Choose the genre', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.genre', verbose_name="The book's genre"),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(help_text='Choose language', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.language', verbose_name="The book's language"),
        ),
    ]
