# Generated by Django 4.0.6 on 2022-07-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(help_text='Select the author', to='catalog.author', verbose_name="Book's author"),
        ),
    ]
